---
info:
  application: RentMe connected trucks Demo
  show: Spring One 2GX 2015

logging:
  level:
    com.netflix.discovery: 'ON'

endpoints:
  restart: enabled

hystrix.command.default.execution.isolation.strategy: SEMAPHORE
